name: zFISHer
channels:
  - conda-forge
dependencies:
  - python=3.10
  - napari
  - pyqt
  - simpleitk
  - pip
  - pip:
    - nd2
    - scikit-image
    - magicgui
    - pandas
    - scipy
    - openpyxl